Repository Javithor360/nexus-workshop, pull requests merged in 2024-10, with the labels that each got.

#30 User, Activities and more controllers
  client/src/main/resources/templates/index.html
  server/src/main/java/com/nexus/server/controllers/ActivityController.java
  server/src/main/java/com/nexus/server/controllers/ActivityTypeController.java
  server/src/main/java/com/nexus/server/controllers/ActivityTypesController.java
  server/src/main/java/com/nexus/server/controllers/AuthController.java
  server/src/main/java/com/nexus/server/controllers/RoleController.java
  server/src/main/java/com/nexus/server/controllers/UserController.java
  server/src/main/java/com/nexus/server/entities/Activity.java
  server/src/main/java/com/nexus/server/entities/Log.java
  server/src/main/java/com/nexus/server/entities/Project.java
  server/src/main/java/com/nexus/server/entities/Role.java
  server/src/main/java/com/nexus/server/entities/User.java
  server/src/main/java/com/nexus/server/repositories/IActivityRepository.java
  server/src/main/java/com/nexus/server/repositories/IProjectRepository.java
  server/src/main/java/com/nexus/server/services/ActivityService.java
  server/src/main/java/com/nexus/server/services/LogService.java
  server/src/main/java/com/nexus/server/services/UserService.java
  server/src/main/resources/SQL/insert_examples.sql
  server/src/main/resources/SQL/nexus_workshop.sql
Labels: enhancement, backend

#34 style: README update and adding LICENSE
  LICENSE
  README.md
Labels: documentation

#35 Dev
  LICENSE
  README.md
  client/pom.xml
  client/src/main/java/com/nexus/client/controllers/DashboardController.java
  client/src/main/java/com/nexus/client/controllers/LoginController.java
  client/src/main/java/com/nexus/client/controllers/MainErrorController.java
  client/src/main/java/com/nexus/client/models/Role.java
  client/src/main/java/com/nexus/client/models/User.java
  client/src/main/java/com/nexus/client/services/UserService.java
  client/src/main/java/com/nexus/client/utils/config/HttpClientConfig.java
  client/src/main/java/com/nexus/client/utils/config/ObjectMapperConfig.java
  client/src/main/java/com/nexus/client/utils/config/SecurityConfig.java
  client/src/main/java/com/nexus/client/utils/security/JwtAuthenticationFilter.java
  client/src/main/resources/application.properties
  client/src/main/resources/templates/dashboard/admin/index.html
  client/src/main/resources/templates/dashboard/admin/info.html
  client/src/main/resources/templates/dashboard/admin/users.html
  client/src/main/resources/templates/dashboard/boss/index.html
  client/src/main/resources/templates/dashboard/employee/index.html
  client/src/main/resources/templates/error/403.html
  client/src/main/resources/templates/error/404.html
  client/src/main/resources/templates/error/500.html
  client/src/main/resources/templates/error/general.html
  client/src/main/resources/templates/index.html
  client/src/main/resources/templates/login.html
  server/src/main/java/com/nexus/server/entities/beans/AuthResponse.java
  server/src/main/java/com/nexus/server/entities/beans/LoginRequest.java
  server/src/main/java/com/nexus/server/services/ActivityService.java
  server/src/main/java/com/nexus/server/services/security/AuthService.java
  server/src/main/java/com/nexus/server/services/security/JwtService.java
  server/src/main/java/com/nexus/server/utils/config/ApplicationConfig.java
  server/src/main/java/com/nexus/server/utils/config/SecurityConfig.java
  server/src/main/java/com/nexus/server/utils/jwt/JwtAuthenticationFilter.java
  server/src/main/resources/SQL/insert_examples.sql
  server/src/main/resources/SQL/nexus_workshop.sql
  src/main/java/com/nexus/controllers/ActivityController.java
  src/main/java/com/nexus/controllers/ActivityTypeController.java
  src/main/java/com/nexus/controllers/ActivityTypesController.java
  src/main/java/com/nexus/controllers/AuthController.java
  src/main/java/com/nexus/controllers/RoleController.java
  src/main/java/com/nexus/controllers/UserController.java
  src/main/java/com/nexus/entities/Activity.java
  src/main/java/com/nexus/entities/Log.java
  src/main/java/com/nexus/entities/Project.java
  src/main/java/com/nexus/entities/Role.java
  src/main/java/com/nexus/entities/User.java
  src/main/java/com/nexus/repositories/IActivityRepository.java
  src/main/java/com/nexus/repositories/IProjectRepository.java
  src/main/java/com/nexus/service/LogService.java
  src/main/java/com/nexus/service/UserService.java
  src/main/resources/application.properties
Labels: enhancement

#46 Refactor Controllers, Replace Placeholders, and Enhance Client Management View
  client/.gitignore
  client/src/main/frontend/main.css
  client/src/main/frontend/package.json
  client/src/main/java/com/nexus/client/controllers/BossDashboardController.java
  client/src/main/java/com/nexus/client/controllers/DashboardController.java
  client/src/main/resources/static/img/BOSS.png
  client/src/main/resources/static/img/EMPLOYEE.png
  client/src/main/resources/static/js/clientManagement.js
  client/src/main/resources/static/js/floatPlaceholder.js
  client/src/main/resources/static/js/jquery-3.7.1.min.js
  client/src/main/resources/static/main.css
  client/src/main/resources/templates/dashboard/admin/clientManagement.html
  client/src/main/resources/templates/dashboard/admin/employeeManagement.html
  client/src/main/resources/templates/dashboard/admin/index.html
  client/src/main/resources/templates/dashboard/boss/clientManagement.html
  client/src/main/resources/templates/fragments/assets/navbar.html
  client/src/main/resources/templates/index.html
  client/src/main/resources/templates/layouts/layoutDashboard.html
Labels: enhancement, frontend

#49 Feature/server fixes and refactorization
  server/src/main/java/com/nexus/server/controllers/ClientController.java
  server/src/main/java/com/nexus/server/controllers/ProjectController.java
  server/src/main/java/com/nexus/server/controllers/UserController.java
  server/src/main/java/com/nexus/server/entities/Activity.java
  server/src/main/java/com/nexus/server/entities/Client.java
  server/src/main/java/com/nexus/server/entities/Project.java
  server/src/main/java/com/nexus/server/entities/User.java
  server/src/main/java/com/nexus/server/repositories/IProjectRepository.java
  server/src/main/java/com/nexus/server/services/ClientService.java
  server/src/main/java/com/nexus/server/services/ProjectService.java
  server/src/main/java/com/nexus/server/services/UserService.java
  server/src/main/java/com/nexus/server/utils/config/SecurityConfig.java
  server/src/main/resources/application.properties
Labels: enhancement, backend

#52 feat: adding asynchronous data listing
  client/src/main/java/com/nexus/client/controllers/LoginController.java
  client/src/main/resources/static/js/clientManagement.js
  client/src/main/resources/static/js/getTokenRequest.js
  client/src/main/resources/templates/dashboard/admin/clientManagement.html
  client/src/main/resources/templates/dashboard/boss/clientManagement.html
Labels: frontend, urgent

#50 Title
  client/.gitignore
  client/pom.xml
  client/src/main/frontend/main.css
  client/src/main/frontend/package-lock.json
  client/src/main/frontend/package.json
  client/src/main/frontend/tailwind.config.js
  client/src/main/java/com/nexus/client/config/ThymeleafConfig.java
  client/src/main/java/com/nexus/client/controllers/BossDashboardController.java
  client/src/main/java/com/nexus/client/controllers/DashboardController.java
  client/src/main/java/com/nexus/client/controllers/LoginController.java
  client/src/main/resources/static/img/BOSS.png
  client/src/main/resources/static/img/EMPLOYEE.png
  client/src/main/resources/static/img/favicon.png
  client/src/main/resources/static/img/logo.png
  client/src/main/resources/static/js/clientManagement.js
  client/src/main/resources/static/js/floatPlaceholder.js
  client/src/main/resources/static/js/getTokenRequest.js
  client/src/main/resources/static/js/jquery-3.7.1.min.js
  client/src/main/resources/templates/dashboard/admin/employeeManagement.html
  client/src/main/resources/templates/dashboard/admin/index.html
  client/src/main/resources/templates/dashboard/admin/projectManagement.html
  client/src/main/resources/templates/dashboard/boss/clientManagement.html
  client/src/main/resources/templates/fragments/assets/navbar.html
  client/src/main/resources/templates/fragments/assets/sidebar.html
  client/src/main/resources/templates/index.html
  client/src/main/resources/templates/layouts/layoutDashboard.html
Labels: frontend

#53 Fix/server cors configuration security config
  README.md
  server/src/main/java/com/nexus/server/utils/config/SecurityConfig.java
Labels: backend

#57 feat: finished CRUD of client management, added CDNs, etc
  client/src/main/frontend/tailwind.config.js
  client/src/main/java/com/nexus/client/controllers/BossDashboardController.java
  client/src/main/resources/static/js/clientManagement.js
  client/src/main/resources/static/js/jQuery-validate.js
  client/src/main/resources/templates/dashboard/boss/clientManagement.html
  client/src/main/resources/templates/error/403.html
  client/src/main/resources/templates/error/404.html
  client/src/main/resources/templates/error/500.html
  client/src/main/resources/templates/error/general.html
  client/src/main/resources/templates/fragments/assets/navbar.html
  client/src/main/resources/templates/layouts/layoutDashboard.html
Labels: enhancement, frontend

#59 fix, server: fixed hibernate Activity entity relation violation
  server/src/main/java/com/nexus/server/entities/Activity.java
  server/src/main/java/com/nexus/server/repositories/IActivityRepository.java
  server/src/main/resources/SQL/insert_examples.sql
  server/src/main/resources/SQL/nexus_workshop.sql
Labels: backend

#62 Feature/server optimizations
  server/src/main/java/com/nexus/server/controllers/ActivityController.java
  server/src/main/java/com/nexus/server/controllers/ProjectController.java
  server/src/main/java/com/nexus/server/controllers/UserController.java
  server/src/main/java/com/nexus/server/entities/beans/AuthResponse.java
  server/src/main/java/com/nexus/server/entities/dto/ActivityDTO.java
  server/src/main/java/com/nexus/server/entities/dto/ProjectDTO.java
  server/src/main/java/com/nexus/server/entities/dto/UserDTO.java
  server/src/main/java/com/nexus/server/repositories/ILogRepository.java
  server/src/main/java/com/nexus/server/services/ActivityService.java
  server/src/main/java/com/nexus/server/services/ProjectService.java
  server/src/main/java/com/nexus/server/services/UserService.java
  server/src/main/java/com/nexus/server/services/extra/DTOConverter.java
  server/src/main/java/com/nexus/server/services/security/AuthService.java
  server/src/main/java/com/nexus/server/services/security/JwtService.java
  server/src/main/resources/application.properties
Labels: enhancement, backend

#66 Feat/fullstack implementations tasks assistance
  client/src/main/java/com/nexus/client/models/Activity.java
  client/src/main/java/com/nexus/client/utils/config/SecurityConfig.java
  client/src/main/resources/static/js/EMPLOYEE/modalProjectDetail.js
  client/src/main/resources/templates/dashboard/employee/projectDetails.html
  client/src/main/resources/templates/index.html
  server/src/main/java/com/nexus/server/controllers/ActivityController.java
  server/src/main/java/com/nexus/server/controllers/UserController.java
  server/src/main/java/com/nexus/server/entities/Activity.java
  server/src/main/java/com/nexus/server/entities/beans/ActivityRequest.java
  server/src/main/java/com/nexus/server/entities/dto/ActivityDTO.java
  server/src/main/java/com/nexus/server/services/ActivityService.java
  server/src/main/java/com/nexus/server/services/ProjectService.java
  server/src/main/java/com/nexus/server/services/extra/DTOConverter.java
  server/src/main/resources/SQL/nexus_workshop.sql
Labels: enhancement, frontend, backend

#70 Fix/boss create project
  client/src/main/resources/static/CSS/formUtils.css
  client/src/main/resources/static/js/BOSS/clientManagement.js
  client/src/main/resources/static/js/BOSS/projectManagementBoss.js
  client/src/main/resources/static/js/EMPLOYEE/modalProjectDetail.js
  client/src/main/resources/static/js/EMPLOYEE/projectManagementEmployee.js
  client/src/main/resources/static/js/floatPlaceholder.js
  client/src/main/resources/templates/dashboard/boss/clientManagement.html
  client/src/main/resources/templates/dashboard/boss/projectDetails.html
  client/src/main/resources/templates/dashboard/boss/projectManagement.html
  client/src/main/resources/templates/dashboard/employee/projectDetails.html
  client/src/main/resources/templates/dashboard/employee/projectManagement.html
Labels: enhancement, frontend

#71 Revert "Fix/boss create project"
  client/src/main/resources/static/CSS/formUtils.css
  client/src/main/resources/static/js/BOSS/clientManagement.js
  client/src/main/resources/static/js/BOSS/projectManagementBoss.js
  client/src/main/resources/static/js/EMPLOYEE/modalProjectDetail.js
  client/src/main/resources/static/js/EMPLOYEE/projectManagementEmployee.js
  client/src/main/resources/static/js/floatPlaceholder.js
  client/src/main/resources/templates/dashboard/boss/clientManagement.html
  client/src/main/resources/templates/dashboard/boss/projectDetails.html
  client/src/main/resources/templates/dashboard/boss/projectManagement.html
  client/src/main/resources/templates/dashboard/employee/projectDetails.html
  client/src/main/resources/templates/dashboard/employee/projectManagement.html
Labels: invalid

#72 Fix/boss create project
  client/src/main/resources/static/js/BOSS/projectManagementBoss.js
  client/src/main/resources/static/js/EMPLOYEE/projectManagementEmployee.js
  client/src/main/resources/static/js/floatPlaceholder.js
  client/src/main/resources/templates/dashboard/boss/projectManagement.html
  client/src/main/resources/templates/dashboard/employee/projectManagement.html
Labels: enhancement, frontend

#79 Feat/dashboard tools controller
  server/src/main/java/com/nexus/server/controllers/DashboardToolController.java
  server/src/main/java/com/nexus/server/entities/beans/DashboardTools.java
  server/src/main/java/com/nexus/server/repositories/IActivityRepository.java
  server/src/main/java/com/nexus/server/repositories/IProjectRepository.java
  server/src/main/java/com/nexus/server/services/DashboardToolService.java
  server/src/main/java/com/nexus/server/services/UserService.java
Labels: backend

#80 fix, server: ran some minor changes
  server/src/main/java/com/nexus/server/controllers/DashboardToolController.java
  server/src/main/java/com/nexus/server/repositories/IProjectRepository.java
  server/src/main/java/com/nexus/server/services/extra/DashboardToolService.java
  server/src/main/java/com/nexus/server/utils/config/SecurityConfig.java
  server/src/main/resources/SQL/insert_examples.sql
Labels: backend

#86 Client optimizations
  client/.gitignore
  client/src/main/resources/static/js/BOSS/projectManagementBoss.js
  client/src/main/resources/static/js/EMPLOYEE/projectManagementEmployee.js
  client/src/main/resources/templates/dashboard/boss/projectDetails.html
  client/src/main/resources/templates/dashboard/employee/projectDetails.html
  client/src/main/resources/templates/dashboard/employee/projectManagement.html
  server/pom.xml
Labels: frontend
